export const slideTypes = {
  song: 'song',
  hymn: 'hymn',
  bible: 'bible',
  text: 'text',
  media: 'media',
  sermon: 'sermon',
  carousel: 'carousel',
}

export const libraryTypes = {
  song: 'song',
  slide: 'slide',
}

export const quickActionsArr = [
  {
    icon: "i-bx-bible",
    name: "Display Bible",
    desc: "Select and open scriptures",
    action: "new-bible",
    // meta: bibleBooks.toString(),
    meta: "",
    bibleBookIndex: 1,
    type: slideTypes.bible,
  },
  {
    icon: "i-bx-search",
    name: "Search Whole Bible",
    desc: "Find scriptures with familiar words",
    action: "new-search-bible",
    meta: "",
    unreleased: false,
    type: slideTypes.bible,
  },
  {
    icon: "i-bx-church",
    name: "Display Hymns",
    desc: "Find verses and chorus to all hymns",
    action: "new-hymn",
    meta: "",
    type: slideTypes.hymn,
  },
  {
    icon: "i-bx-music",
    name: "Display Song Lyrics",
    desc: "Find lyrics to any song, native too",
    action: "new-song",
    meta: "",
    type: slideTypes.song,
  },
  {
    icon: "i-bx-text",
    name: "Create Text Slide",
    desc: "Create slides with notes and more",
    action: "new-slide",
    meta: "",
    type: slideTypes.text,
  },
  {
    icon: "i-bx-image",
    name: "Add Media",
    desc: "Display video or image media",
    action: "new-media",
    meta: "",
    type: slideTypes.media,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-save",
    name: "Add to Library",
    desc: "Save your favorite songs, slides",
    action: "new-library",
    meta: "save files images pictures videos songs documents",
    type: slideTypes.media,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-info-circle",
    name: "Add Banners/Alert",
    desc: "Notify your audience without disruption",
    action: "new-alert",
    meta: "",
    // unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-lucide-music-2",
    name: "Add Song",
    desc: "Save songs to your personal library",
    action: "add-song",
    meta: "",
    // unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-trash",
    name: "Remove Alert",
    desc: "Remove current alert",
    action: "remove-alert",
    searchableOnly: true,
    meta: "trash alert remove banner",
    // unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-time",
    name: "Add Countdown Timer",
    desc: "Find scriptures with familiar words",
    action: "new-timer",
    meta: "",
    unreleased: true,
    type: slideTypes.text,
  },
  {
    icon: "i-ph-file-ppt",
    name: "Import Slides",
    desc: "Extract from other apps like PowerPoint",
    action: "new-transcribe",
    meta: "power point Google slides",
    unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-carousel",
    name: "Add Slideshow/Carousel",
    desc: "Find scriptures with familiar words",
    action: "new-carousel",
    meta: "",
    unreleased: true,
    type: slideTypes.text,
  },
  {
    icon: "i-material-symbols-speech-to-text",
    name: "Transcribe Sermon",
    desc: "Start transcribing preacher sermons",
    action: "new-transcribe",
    meta: "",
    unreleased: true,
    // type: slideTypes.text
  },
  // {
  //   icon: "i-carbon-overlay",
  //   name: "Add Overlay",
  //   desc: "Place one-third of a slide over another",
  //   action: "new-overlay",
  //   meta: "",
  //   unreleased: true,
  //   // type: slideTypes.text
  // },
]

export const slideLayoutTypes = {
  heading_sub: 'heading-and-subtitle',
  full_text: 'full-text',
  two_column: 'two-column',
  bible: 'bible',
  empty: 'empty',
}

export const backgroundTypes = {
  solid: 'solid',
  gradient: 'gradient',
  image: 'image',
  video: 'video'
}

export const backgroundFillTypes = {
  fit: 'Fit',
  crop: 'Crop',
  stretch: 'Stretch',
  center: 'Center',
}

export const bibleBooks = [
  "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
  "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
  "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra",
  "Nehemiah", "Esther", "Job", "Psalms", "Proverbs",
  "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah",
  "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel",
  "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk",
  "Zephaniah", "Haggai", "Zechariah", "Malachi",
  "Matthew", "Mark", "Luke", "John", "Acts of the Apostles",
  "Romans", "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
  "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy",
  "2 Timothy", "Titus", "Philemon", "Hebrews", "James",
  "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude",
  "Revelation"
];

export const bibleVersions = [
  'KJV',
  // 'NKJV', 
  // 'NIV', 
  // 'AMP'
]

export const appFonts = [
  'Inter',
  'Roboto',
  'Raleway',
  'Bebas Neue',
  'Overpass',
  'Playfair Display',
  'Sedan',
  'Montserrat',
  'Jersey 25',
  'Nunito',
  'IBM Plex Sans',
  'Jost',
  'EB Garamond',
  'Dancing Script',
  'Slabo',
  'IBM Plex Serif',
  'Great Vibes',
  'Playball',
  'Saira Extra Condensed',
  'Lato'
]

export const churchesArr = [
  // "Other Church",
  "Redeemed Christian Church of God (RCCG)",
  "Living Faith Church Worldwide (Winners' Chapel)",
  "Deeper Christian Life Ministry",
  "Christ Embassy",
  "Mountain of Fire and Miracles Ministries (MFM)",
  "Catholic Church in Nigeria",
  "Anglican Church of Nigeria",
  "House on the Rock Church",
  "Daystar Christian Centre",
  "The Apostolic Church Nigeria",
  "The Salvation Army Nigeria",
  "Mountain of Salvation Prayer Ministry",
  "Christ Apostolic Church (CAC)",
  "Methodist Church Nigeria",
  "Presbyterian Church of Nigeria",
  "Assemblies of God Nigeria",
  "The Church of Jesus Christ of Latter-day Saints in Nigeria",
  "Christian Reformed Church in Nigeria",
  "The Foursquare Gospel Church in Nigeria",
  "Cherubim and Seraphim Movement Church",
  "Celestial Church of Christ",
  "Mountain of Glory Ministry",
  "Christ Apostolic Church (Worldwide)",
  "The Lord's Chosen Charismatic Revival Movement",
  "Salvation Ministries",
  "Global Impact Church",
  "The Fountain of Life Church",
  "Assemblies of God",
  "Harvesters International Christian Centre",
  "Household of God Church",
  "The Word Bible Church",
  "Omega Fire Ministries",
  "Gloryland Church",
  "United Methodist Church Nigeria",
  "Rivers of Living Waters Ministries",
  "Grace Family International Church",
  "Commonwealth of Zion Assembly (COZA)",
  "Christian Pentecostal Mission (CPM)",
  "The Apostolic Church Nigeria - Bethel Area",
  "Faith Tabernacle Church",
  "Rhema Chapel International Churches",
  "Jesus Embassy International",
  "Dominion City Church",
  "House of Grace",
  "Liberty Christian Centre",
  "The Redeemed Evangelical Mission (TREM)",
  "Royal House of Grace",
  "Lighthouse Chapel International",
  "Jesus Dominion International",
  "Green Pastures Christian Centre",
  "Holy Ghost Christian Centre",
  "Salem International Christian Centre",
  "Christ LivingSpring Apostolic Ministry (CLAM)",
  "Faithway Baptist Church",
  "Full Gospel Business Men's Fellowship International (FGBMFI)",
  "Restoration Chapel International",
  "Word of Life Bible Church",
  "Fountain of Wisdom Ministries",
  "Shepherd's House Assembly International",
  "Trinity Church",
  "Elevation Church",
  "Christ Power and Authority Church",
  "Lifehouse Pentecostal Assembly",
  "Faith Clinic International Church",
  "Jesus Sanctuary Evangelical Church",
  "Word of Faith Christian Centre",
  "The New Covenant Church",
  "Kingdom Life Gospel Outreach Church",
  "The New Testament Assembly",
  "Kingdom Embassy International Church",
  "Faith City Church",
  "All Nations Baptist Church",
  "Grace Covenant Assembly",
  "The Apostolic Faith Church",
  "St. Andrews Anglican Church",
  "St. Joseph Catholic Church",
  "Covenant Cathedral International Church",
  "Word of Life Bible Church",
  "Latter Rain Assembly",
  "Celebration Church",
  "Praise Chapel International",
  "Christ International Church",
  "Grace Family Chapel International",
  "Royal Connections Assembly",
  "New Wine Church",
  "Glorious Light International Church",
  "Christ Apostolic Church (House of Refuge)",
  "House of Praise International Church",
  "Redemption Tabernacle Christian Centre",
  "Global Harvest Church",
  "Dunamis International Gospel Centre",
  "Believers Loveworld",
  "Pentecostal Fellowship of Nigeria (PFN)",
  "Church of Nigeria (Anglican Communion)"
]
