export const slideTypes = {
  sermon: 'sermon',
  lyrics: 'lyrics',
  hymn: 'hymn',
  carousel: 'carousel',
  bible: 'bible',
  text: 'text'
}

export const quickActionsArr = [
  {
    icon: "i-bx-bible",
    name: "Display Bible",
    desc: "Select and open scriptures",
    action: "new-bible",
    // meta: bibleBooks.toString(),
    meta: "",
    bibleBookIndex: 1,
    type: slideTypes.bible,
  },
  {
    icon: "i-bx-church",
    name: "Display Hymns",
    desc: "Find verses and chorus to all hymns",
    action: "new-hymn",
    meta: "",
    type: slideTypes.hymn,
  },
  {
    icon: "i-bx-music",
    name: "Display Lyrics",
    desc: "Find lyrics to any song, native too",
    action: "new-lyrics",
    meta: "",
    type: slideTypes.lyrics,
  },
  {
    icon: "i-bx-slideshow",
    name: "Create Slide",
    desc: "Create slides for sermons and more",
    action: "new-slide",
    meta: "",
    type: slideTypes.text,
  },
  {
    icon: "i-bx-search",
    name: "Search Bible",
    desc: "Find scriptures with familiar words",
    action: "new-bible-search",
    meta: "",
    unreleased: true,
    type: slideTypes.bible,
  },
  {
    icon: "i-bx-image",
    name: "Add Media",
    desc: "Display video or image media",
    action: "new-media",
    meta: "",
    unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-carbon-overlay",
    name: "Add Overlay",
    desc: "Place one-third of a slide over another",
    action: "new-overlay",
    meta: "",
    unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-ph-file-ppt",
    name: "Import Slides",
    desc: "Extract from other apps like PowerPoint",
    action: "new-transcribe",
    meta: "power point Google slides",
    unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-carousel",
    name: "Add Slideshow/Carousel",
    desc: "Find scriptures with familiar words",
    action: "new-carousel",
    meta: "",
    unreleased: true,
    type: slideTypes.text,
  },
  {
    icon: "i-material-symbols-speech-to-text",
    name: "Transcribe Sermon",
    desc: "Start transcribing preacher sermons",
    action: "new-transcribe",
    meta: "",
    unreleased: true,
    // type: slideTypes.text
  },
  {
    icon: "i-bx-time",
    name: "Add Countdown Timer",
    desc: "Find scriptures with familiar words",
    action: "new-timer",
    meta: "",
    unreleased: true,
    type: slideTypes.text,
  },
]

export const slideLayoutTypes = {
  heading_sub: 'heading-and-subtitle',
  full_text: 'full-text',
  two_column: 'two-column',
  bible: 'bible',
}

export const backgroundTypes = {
  solid: 'solid',
  gradient: 'gradient',
  image: 'image',
  video: 'video'
}

export const bibleBooks = [
  "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
  "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
  "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra",
  "Nehemiah", "Esther", "Job", "Psalms", "Proverbs",
  "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah",
  "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel",
  "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk",
  "Zephaniah", "Haggai", "Zechariah", "Malachi",
  "Matthew", "Mark", "Luke", "John", "Acts of the Apostles",
  "Romans", "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
  "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy",
  "2 Timothy", "Titus", "Philemon", "Hebrews", "James",
  "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude",
  "Revelation"
];

export const hymnTitles = [
  "1 All Your Anxiety",
  "2 Come Unto Me",
  "3 Impatient Heart Be Still",
  "4 Leave It There",
  "5 Never Give Up",
  "6 Yield Not To Temptation",
  "7 Turn Your Eyes Unto Jesus",
  "8 Blessed Be The Name",
  "9 Great Is Thy Faithfulness",
  "10 Oh For A Thousand",
  "11 Holy Holy Holy",
  "12 Praise Him Praise Him Jesus Our Blessed",
  "13 To God Be The Glory",
  "14 How Great Thou Art",
  "15 O Worship The King",
  "16 If God Be For Us",
  "17 Nothing But The Blood",
  "18 Blessed Assurance",
  "19 Christ Jesus Hath The Power",
  "20 The Way The Truth The Life",
  "21 Will Your Anchor Hold",
  "22 Simply Trusting Everyday",
  "23 No Other Plea",
  "24 It Is Well With My Soul",
  "25 Now I Belong To Jesus",
  "26 I Know Whom I Have Believed",
  "27 I Am Bound For Canan",
  "28 I Am Living In Cannan",
  "29 I Know Who Holds Tomorrow",
  "30 I've Anchored In Jesus",
  "31 He Touched Me",
  "32 Heaven Came Down",
  "33 Since Jesus Came Into My Heart",
  "34 Constantly Abiding",
  "35 A New Name In Glory",
  "36 My Name's Written There",
  "37 When I See The Blood",
  "38 Have You Been To Jesus",
  "39 Power In The Blood",
  "40 Wash Me O Lamb Of God",
  "41 Onward Christian Soldiers",
  "42 Close To Thee",
  "43 Trust And Obey",
  "44 Come Over",
  "45 Jesus My Strengh My Hope",
  "46 A Christian Home",
  "47 Just Obey",
  "48 Tis So Sweet To Trust",
  "49 Let Others See Jesus In You",
  "50 Count Your Blessings",
  "51 That Blessed Canan Land",
  "52 Count Me",
  "53 So Send I You",
  "54 I Am Ready For Service",
  "55 Anywhere With Jesus",
  "56 I Love My Master",
  "57 They That Wait Upon The Lord",
  "58 The Last Mile Of The Way",
  "59 Little Is Much When God Is In It",
  "60 Where Could I Go",
  "61 Lord Speak To Me",
  "62 Go Labor On",
  "63 Will There Be Any Stars",
  "64 The Old Rugged Cross",
  "65 Oh How I Love Jeus",
  "66 Jesus Is The Sweetest",
  "67 My Jesus I Love Thee",
  "68 Like A Shepherd Lead Us",
  "69 Christ Be Beside Me",
  "70 Have You Any Room For Jesus",
  "71 I Want To See Jesus Dont You",
  "72 The Solid Rock",
  "73 Jesus Only Is Our Message",
  "74 The Heart That Was Broken For Me",
  "75 The Church's One Foundation",
  "76 In Times Like These",
  "77 I Have Decided To Follow Jesus",
  "78 Faith Of Our Fathers",
  "79 The Way Of The Cross",
  "80 At The Cross",
  "81 Lead Me To Calvary",
  "82 When I Survey The Wondrous Cross",
  "83 Thy Word Have I Hid In My Heart",
  "84 Deeper Deeper In The Love Of Jesus",
  "85 Give Of Your Best To The Master",
  "86 Nothing Between",
  "87 Take My Life",
  "88 Wherever He Leads I'll Go",
  "89 O Jesus I Have Promised",
  "90 Oh Love That Will Not Let Me Go",
  "91 Where He Leads Me",
  "92 I Surrender All",
  "93 More Love To Thee",
  "94 Draw Me Nearer Blessed Jesus",
  "95 Come Saviour Jesus From Above",
  "96 Peace Be Still",
  "97 Oft In Danger Oft In Woe",
  "98 The Song Of The Solider",
  "99 There Is Victory Within My Soul",
  "100 Christ Our Mighty Captain",
  "101 My Father Knows",
  "102 The Healer",
  "103 He Healed Them All",
  "104 Tell Somebody",
  "105 I'll Tell The World",
  "106 Tell The Whole Wide",
  "107 Send The Gospel Light",
  "108 Must I Go And Empty Handed",
  "109 To The Work",
  "110 Till The Whole World Knows",
  "111 Rescue The Perishing",
  "112 Win Them One By One",
  "113 Go And Tell The Story",
  "114 Brighten The Corner Where You Are",
  "115 Lift Him Up",
  "116 Carry Your Bible",
  "117 Show A Little Bit Of Love And Kindness",
  "118 I Love To Tell The Story",
  "119 Do Something For Others",
  "120 Speak A Word For Jesus",
  "121 Somebody Else Needs Him Too",
  "122 Somebody Needs Your Love",
  "123 No One Like My Saviour",
  "124 Christ Receiveth Sinful Men",
  "125 Wondeful Grace Of Jesus",
  "126 Great God Of Wonders",
  "127 Rock Of Ages Cleft For Me",
  "128 Vicory In Jesus",
  "129 Grace Greater Than Our Sin",
  "130 Just As I Am Without One Plea",
  "131 In Tenderness He Sought Me",
  "132 Running Over",
  "133 Out Of My Bondage",
  "134 And Can It Be That I Should Gain",
  "135 Tell Me The Old Old Story",
  "136 At Calvary",
  "137 How Beautiful Heaven Must Be",
  "138 When We All Get To Heaven",
  "139 Beautiful Home",
  "140 Laying My Treasure Up There",
  "141 I Shall See The King",
  "142 Holy Holy Is What The Angels Sing",
  "143 The End Of The Road",
  "144 I Wont Have To Cross Jordan Alone",
  "145 When They Ring The Golden Bell",
  "146 Face To Face",
  "147 Sweet By And By",
  "148 No Tears In Heaven",
  "149 Farther Along",
  "150 Pentecostal Power",
  "151 There Shall Be Showers Of Blessing",
  "152 Joys Are Flowing Like A River",
  "153 With Signs Following",
  "154 Give Me A Double Portion",
  "155 Let Jesus Come Into Your Heart",
  "156 Room At The Cross For You",
  "157 Wandering Child O Come Home",
  "158 Come Believing",
  "159 Why Do You Wait",
  "160 The Shepherd Of Love",
  "161 Who'll Be The Next To Follow Jesus",
  "162 Almost Persuaded",
  "163 My God Is An Hour So Sweet",
  "164 Prayer Is The Soul S Sincere Desire",
  "165 Guide Me O Thou Great Jehovah",
  "166 Did You Think To Pray",
  "167 I Must Tell Jesus",
  "168 I Need Thee Every Hour",
  "169 What A Friend We Have In Jesus",
  "170 Sweet Hour Of Prayer",
  "171 Pass Me Not",
  "172 When The Roll Is Called Up Yonder",
  "173 Is It The Crowning Day",
  "174 Jesus Is Coming Again",
  "175 He Is Comimg Again",
  "176 Christ Returneth",
  "177 Search Me O God",
  "178 Fill My Cup Lord",
  "179 Higher Ground",
  "180 Since The Son Hath Made Me Free",
  "181 All Things Are Possible",
  "182 Blessed Are The Pure In Heart",
  "183 Come O My God The Promise Seal",
  "184 Saviour From Sin I Wait To Prove",
  "185 The Thing My God Doth Hate",
  "186 God Of All Power And Truth And Grace",
  "187 Jesus All Atoning Lamb",
  "188 O Lord How Happy Should We Be",
  "189 Take Time To Be Holy",
  "190 Called Unto Holiness",
  "191 Come Holy Ghost All Quickening Fire",
  "192 O For A Heart To Praise My God",
  "193 Another Year",
  "194 O Day Of Rest And Gladness",
  "195 Another Year Is Dawning",
  "196 Does Jesus Care",
  "197 Love Found A Way",
  "198 His Love Can Never Fail",
  "199 Resting In His Love",
  "200 The Ninety And Nine",
  "201 Love Lifted Me",
  "202 Wonderful Story Of Love",
  "203 There Is No Love Like The Love Of Jesus",
  "204 Ye Must Be Born Again",
  "205 Have You Counted The Cost",
  "206 Where Will You Spend Eternity",
  "207 There's A Great Day Coming",
  "208 The Great Judgement Morning",
  "209 I Will Not Forget Thee",
  "210 Open My Eyes That I May See",
  "211 Crown Him With Many Crowns",
  "212 Jesus Shall Reign",
  "213 Rejoice The Lord Is King",
  "214 All Hail The Power Of Jesus",
  "215 Ohappy Day That Fixed My Choice",
  "216 More About Jesus Would I Know",
  "217 O Perfect Love All Human Thought Transcending",
  "218 Love Divine All Loves",
  "219 More More Holiness Give Me",
  "220 When I Saw The Cleansing Fountain",
  "221 Lets Not Thy Hands Be Slack",
  "222 Speed Thy Servants Saviour Speed Them",
  "223 I Gave My Life For Thee",
  "224 Oh The Bitter Shame And Sorrow",
  "225 Burn Fire Of God",
  "226 Thy Blessed Will Divine",
  "227 Nearer My God To Thee",
  "228 O Why Not Tonight",
  "229 Hold The Fort",
  "230 Bring Your Vessel Not A Few",
  "231 Send The Light",
  "232 Blest Be The Tie That Binds",
  "233 Stand Up Stand Up For Jesus",
  "234 O Lord With One Accord",
  "235 The Holy Spirit's Power",
  "236 Lord God The Holyghost",
  "237 Peace Perfect Peace",
  "238 Thou Hidden Source Of Calm Repose",
  "239 One There Is Above All Others",
  "240 Jesus Is The Same Forever",
  "241 I've Found The Pearl Of Greatest Peice",
  "242 A Good High Priest Is Come",
  "243 Standing On The Promises",
  "244 All Things In Jesus",
  "245 Is Your Life A Channel Of Blessing",
  "246 O Brother Life S Journey Beginning",
  "247 The Finished The Messiah Dies",
  "248 The Mercy Seat",
  "249 Come Sing The Praise Of Jesus",
  "250 For My Sake And The Gospel S Go",
  "251 Only Remembered",
  "252 It Is Morning In My Heart",
  "253 My Portion Forever",
  "254 Lower And Lower",
  "255 Let The Fire Fall",
  "256 Redeemed",
  "257 Jesus Send More Labourers",
  "258 Oh To Be Like Thee",
  "259 More Like The Master",
  "260 Gracious Spirit Dwell With Me"
]